function SummarySection({
  summary,
  copySummary,
  downloadSummary,
}) {
  if (!summary) return null;

  return (
    <div className="mt-10 overflow-hidden rounded-3xl shadow-xl border border-gray-200 bg-white">

      <div className="bg-gradient-to-r from-purple-600 to-indigo-700 text-white px-6 py-5 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">

        <div>
          <h3 className="text-2xl font-bold">
            📑 AI Summary
          </h3>

          <p className="text-purple-100 text-sm mt-1">
            Generated by Prepzy AI
          </p>
        </div>

        <div className="flex gap-3">

          <button
            onClick={copySummary}
            className="bg-white/20 hover:bg-white/30 px-4 py-2 rounded-lg transition"
          >
            📋 Copy
          </button>

          <button
            onClick={downloadSummary}
            className="bg-white text-purple-700 font-semibold px-4 py-2 rounded-lg hover:bg-purple-100 transition"
          >
            ⬇ Download
          </button>

        </div>

      </div>

      <div className="p-8 bg-gray-50">
        <pre className="whitespace-pre-wrap text-gray-700 leading-8 text-[16px]">
          {summary}
        </pre>
      </div>

    </div>
  );
}

export default SummarySection;